#!/usr/bin/env python3
"""
Chat Auto-Save - Automatically saves Cursor chat conversations
"""

import os
import json
import shutil
from datetime import datetime
from pathlib import Path

def save_chat_conversation():
    """Save current conversation context."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    
    # Create backup directory
    backup_dir = Path(__file__).parent / "chat_backups"
    backup_dir.mkdir(exist_ok=True)
    
    # Create conversation file
    conversation_file = backup_dir / f"conversation_{timestamp}.md"
    
    content = f"""# Cursor Chat Conversation - {timestamp}

## Conversation Context
- **Date**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
- **Project**: {Path(__file__).parent.name}

## Recent Activity
- Working on quote automation system
- Investigating Pipedrive sub-organizations for quote creation
- Focusing on organizations with HID-QBO-Status = "QBO-SubCust"

## Key Files
- `quote_monitor.py` - Main quote monitoring script
- `pipedrive.py` - Pipedrive API integration
- `quote_automation_requirements.md` - Requirements documentation

---
*Auto-generated by chat_auto_save.py*
"""
    
    with open(conversation_file, 'w') as f:
        f.write(content)
    
    print(f"✅ Conversation saved: {conversation_file}")
    return conversation_file

if __name__ == "__main__":
    save_chat_conversation()
